sylius_grid:
    grids:
        setono_sylius_callout_admin_callout:
            driver:
                options:
                    class: "%setono_sylius_callout.model.callout.class%"
            sorting:
                priority: asc
            fields:
                code:
                    type: string
                    label: setono_sylius_callout.ui.code
                    sortable: ~
                name:
                    type: string
                    label: setono_sylius_callout.ui.name
                    sortable: ~
                enabled:
                    type: twig
                    label: setono_sylius_callout.ui.enabled
                    sortable: ~
                    options:
                        template: '@SyliusUi/Grid/Field/enabled.html.twig'
                priority:
                    type: twig
                    label: setono_sylius_callout.ui.priority
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                updatedAt:
                    type: datetime
                    label: setono_sylius_callout.ui.updated_at
                    sortable: ~
                    options:
                        format: "Y-m-d H:i:s"
                rulesAssignedAt:
                    type: datetime
                    label: setono_sylius_callout.ui.rules_assigned_at
                    sortable: ~
                    options:
                        format: "Y-m-d H:i:s"
            filters:
                name:
                    type: string
                    label: setono_sylius_callout.ui.name
                rule:
                    type: entities
                    label: setono_sylius_callout.ui.rule
                    form_options:
                        class: "%setono_sylius_callout.model.callout_rule.class%"
                    options:
                        field: "rules.id"
                date:
                    type: date
                    label: sylius.ui.date
                    options:
                        field: endsAt
                        inclusive_to: true
            actions:
                main:
                    create:
                        type: create
                    assign:
                        type: setono_callout_default
                        label: setono_sylius_callout.ui.action.assign
                        options:
                            icon: sync
                            color: red
                            link:
                                route: setono_sylius_callout_admin_callout_assign
                item:
                    update:
                        type: update
                    callouts_product_list:
                        type: callouts_product_list
                        label: setono_sylius_callout.ui.callouts_product_list
                    delete:
                        type: delete
