imports:
    - { resource: "@SetonoSyliusCalloutPlugin/Resources/config/grids/setono_sylius_callout_admin_callout.yaml" }
      
sylius_grid:
    templates:
        action:
            setono_callout_default: "@SetonoSyliusCalloutPlugin/Admin/Grid/Action/setono_callout_default.html.twig"
            callouts_product_list: "@SetonoSyliusCalloutPlugin/Admin/Grid/Action/calloutsProductList.html.twig"
